export default class Url {
  static UserLogin = '/Member/UserLogin'
  static UserSmsLogin = '/Member/UserSmsLogin'
  static FindPassword = '/Member/FindPassword'
  static SendSMS = '/Member/SendSMS'
  static PersonalDetail ='/Member/Detail'
  static UserLogout = '/Member/UserLogout'
  static PersonalCenter = '/Member/PersonalCenter'
  static BorrowList = '/Loan/BorrowList_New'
  static LendList = '/Loan/LendList_New'
  static IncomeRepaymentPlan = '/Loan/IncomeRepaymentPlan'
  static IouDetail = '/Loan/Detail'
  static IncomeRepaymentPlanDetail = '/Loan/IncomeRepaymentPlanDetail'
  static TransferALL = '/Member/TransferALL'
  static ThisMonthTransferALL = '/Member/ThisMonthTransferALL'
  static UpdatePaymentPwd = '/Member/UpdatePaymentPwd'
  static ForgetPaymentPwd = '/Member/ForgetPaymentPwd'
  static BankCardList = '/Member/BankCardList'
  static Index = '/Common/Index'
  static CreateSys = '/Loan/Create_Sys'
  static LoanCollectionCancel = '/Loan/LoanCollectionCancel'
  static ConfirmLoan = '/Loan/ConfirmLoan'
  static CancelAccount = '/Loan/CancelAccount'
  static LoanCenterList = '/Loan/LoanCenterList'
  static Opinion = '/Member/Opinion'
  // BM
  static BindCard = '/BM/account/reg.c'
  static queryBalance = 'BM/query/balanceAction.c'
}
