module.exports = {
  content: '选择所属银行',
  router: true,
  vuex: {
    mutations: false,
    state: false
  },
  class: {
    'BM': false,
    'Btn': false,
    'Check': false,
    'Http': false,
    'Mock': false,
    'Router': true,
    'Stata': false,
    'Status': false,
    'Storage': true,
    'Time': false,
    'Type': false,
    'Url': false
  },
  components: {
    'billboard': `[
        {
          svg: 'chuyin',
          key: '中国工商银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '农业银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '中国银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '建设银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '交通银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '中信银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '光大银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '华夏银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '邮政储蓄',
          target: ''
        }, {
          svg: 'chuyin',
          key: '恒丰银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '农村合作社',
          target: ''
        }, {
          svg: 'chuyin',
          key: '徽商银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '浦发银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '兴业银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '招商银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '平安股份有限公司',
          target: ''
        }, {
          svg: 'chuyin',
          key: '广东发展银行',
          target: ''
        }, {
          svg: 'chuyin',
          key: '民生银行',
          target: ''
        }
      ]`,
    'board': false,
    'button': false,
    'deadline': false,
    'detail-list': false,
    'image-bg': false,
    'inputs': false,
    'keyboard': false,
    'modals': false,
    'nav': false,
    'pay-password': false,
    'pull-refresh': false,
    'receipt': false,
    'tab': false,
    'tip': `{
        type: 'default',
        content: '常用'
      }`,
    'title': `{
        contentText: '选择所属银行'
      }`,
    'without': false,
    'work-card': false
  }
}
